name: Run Gauge Tests

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - demo
          - prelive
          - live

jobs:
  gauge-test:
    strategy:
      matrix:
        environment: [qa, demo, prelive, live]
      fail-fast: false # Continue with other environments if one fails

    runs-on: ubuntu-latest
    name: Deploy to ${{ matrix.environment }}

    # Optional: Add environment protection for sensitive environments
    environment:
      name: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Setup Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-version: '1.6.14'

      - name: Install Gauge plugins
        run: |
          gauge install java -v 0.11.3
          gauge install json-report -v 0.4.0

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Gauge Test
        run: mvn com.thoughtworks.gauge.maven:gauge-maven-plugin:1.6.3:execute

      # Environment-specific configurations
      - name: Configure for QA
        if: matrix.environment == 'qa'
        run: |
          echo "Setting QA-specific configurations"
          # Add QA-specific configurations here
          echo "QA_SERVER_URL=https://qa.example.com" >> $GITHUB_ENV

      - name: Configure for Demo
        if: matrix.environment == 'demo'
        run: |
          echo "Setting Demo-specific configurations"
          # Add Demo-specific configurations here
          echo "DEMO_SERVER_URL=https://demo.example.com" >> $GITHUB_ENV

      - name: Configure for Prelive
        if: matrix.environment == 'prelive'
        run: |
          echo "Setting Prelive-specific configurations"
          # Add Prelive-specific configurations here
          echo "PRELIVE_SERVER_URL=https://prelive.example.com" >> $GITHUB_ENV

      - name: Configure for Live
        if: matrix.environment == 'live'
        run: |
          echo "Setting Live-specific configurations"
          # Require manual approval for production deployment
          echo "LIVE_SERVER_URL=https://live.example.com" >> $GITHUB_ENV
