name: Java CI with Maven

on:
  schedule:
    - cron: * * * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run Gauge Test
        run: mvn com.thoughtworks.gauge.maven:gauge-maven-plugin:1.6.3:execute